const studentProfileInitialValue = {
    name: "",
    dob: "",
    email: "",
    mobile: "",
    admissnumber: "",
    gender: "",
    fathername: "",
    mothername: "",
    fatheroccupation: "",
    motheroccupation: "",
    corresaddress: "",
    correscity: "",
    corresstate: "",
    correspcode: "",
    checkbox: false,
    permaaddress: "",
    permacity: "",
    permastate: "",
    permapcode: "",
    classvalue: "",
    section: "",
    teachername: "",
    fathermobileno: "",
    alternatephoneno: "",
    image: {},
}

const studentSearchInitialValue = {
    name: "",
    classvalue: "",
    section: "",
    subject: "",
    attachment: [],
}
export { studentProfileInitialValue, studentSearchInitialValue };