const drawercontent= [
    {
      content:'Students',web:'student',
      activeimage:'person_active.png',
      inactiveimage:"person_inactive.png",
      subcontent:[{content:'Find a student',web:'studentsearch',clicked:false}],
      clicked:false,
      key:1
    },
    {
      content:'Teacher',
      web:'teacher',
      activeimage:'people_active.png',
      inactiveimage:"people_inactive.png",
      subcontent:[{content:'Find a teacher',web:'teachersearch',clicked:false}],clicked:false,key:2},
    {
      content:'Gallery',
      web:'gallery',
      activeimage:'gallery_active.png',
      inactiveimage:"gallery_inactive.png",
      subcontent:[],
      clicked:false,
      key:3
    },
    {
      content:'Time table',
      web:'timetable',
      activeimage:'timetable_active.png',
      inactiveimage:"timetable_inactive.png",
      subcontent:[],
      clicked:false,
      key:4},
    {
      content:'Exams',
      web:'exam',
      activeimage:'exam_active.png',
      inactiveimage:"exam_inactive.png",
      subcontent:[
        {content:'Schedule an exam',web:'exam',clicked:false},
        {content:'Arrange exam duty',web:'examduty',clicked:false}
      ],
      clicked:false,
      key:5
    },
    {
      content:'Syllabus',
      web:'syllabus',
      activeimage:'syllabus_active.png',
      inactiveimage:"syllabus_inactive.png",
      subcontent:[],
      clicked:false,
      key:6},
    {
      content:'Results',
      web:'result',
      activeimage:'done_inactive.png',
      inactiveimage:"done_inactive.png",
      subcontent:[],
      clicked:false,
      key:7},
    {
      content:'Calendar events',
      web:'event',
      activeimage:'event_active.png',
      inactiveimage:"event_inactive.png",
      subcontent:[],
      clicked:false,
      key:8
    },
    {
      content:'Check tickets',
      web:'ticket',
      activeimage:'noti.png',
      inactiveimage:"noti.png",
      subcontent:[],
      clicked:false,
      key:9
    },
    {
      content:'Communication',
      activeimage:'chat_inactive.png',
      inactiveimage:"chat_inactive.png",
      subcontent:[],
      clicked:false,
      key:10},
    {
      content:'Fees',
      web:'fee',
      activeimage:'coin_inactive.png',
      inactiveimage:"coin_inactive.png",
      subcontent:[],
      clicked:false,
      key:11
    },
    {
      content:'School Profile',
      web:'schoolprofile',
      activeimage:'schoolprofile_inactive.png',
      inactiveimage:"schoolprofile_inactive.png",
      subcontent:[],
      clicked:false,
      key:12
    },
    {
      content:'Circular',
      web:'circular',
      activeimage:'circular_inactive.png',
      inactiveimage:"circular_inactive.png",
      subcontent:[],
      clicked:false,
      key:13
    },
  ];
export default drawercontent;